on:
  push:
  workflow_dispatch:
env:
  PYTHON_VERSION: "3.10"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Create file
      run: |
        mkdir -p data/big
        echo "BIG FILE" > data/big/file.txt
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: big-file
        path: data/big/file.txt
    
  consume:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: big-file
        path: docs-sphinx/lite/pypi
    - name: Debug
      run: |
        ls -R
