name: Build Test

on:
  workflow_dispatch:

concurrency:
  group: build-test-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  Linux:
    strategy:
      matrix:
        python-version:
            - '3.10'
            - '3.9'
    runs-on: ubuntu-18.04
    env:
      PIP_ONLY_BINARY: cmake
      NUMPY_VERSION: ${{ matrix.numpy-version }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}-${{ matrix.os }}-${{matrix.python-version}}-${{matrix.numpy-version}}
    - name: Use ccache
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
    - name: Find gcc
      run: which gcc
    - name: Find g++
      run: which g++
