name: Docs
on:
  pull_request:

jobs:
  Sphinx:
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@v3
          with:
            submodules: true
        - name: Print head_ref
          run: echo "${{ github.head_ref }}"
        - name: Print ref
          run: echo "${{ github.ref }}"
        - name: Print ref
          run: echo "${{ github.head_ref || github.ref }}"
